.TH "ColorPickButton" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorPickButton \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definegamedialog.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorPickButton\fP (int i, QWidget *parent)"
.br
.ti -1c
.RI "int \fBgetIndex\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file definegamedialog.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ColorPickButton::ColorPickButton (inti, QWidget *parent)\fC [inline]\fP"
.PP
Definition at line 14 of file definegamedialog.h.
.SH "Member Function Documentation"
.PP 
.SS "int ColorPickButton::getIndex () const\fC [inline]\fP"
.PP
Definition at line 16 of file definegamedialog.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
