.TH "/home/nathan/workspace/cooperation/competitorwidget.h" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nathan/workspace/cooperation/competitorwidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui>\fP
.br
\fC#include 'guicommon.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompetitorWidget\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
