.TH "/home/nathan/workspace/cooperation/competitorshape.h" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nathan/workspace/cooperation/competitorshape.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompetitorShape\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBShape\fP { \fBsquare\fP, \fBcircle\fP, \fBsphere\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBShape\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIsquare \fP\fP
.TP
\fB\fIcircle \fP\fP
.TP
\fB\fIsphere \fP\fP

.PP
Definition at line 8 of file competitorshape.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
