.TH "CompetitorShape" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompetitorShape \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <competitorshape.h>\fP
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBexecuteUpdate\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompetitorShape\fP (int initialLength, QColor &color, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetRadius\fP (int radius)"
.br
.ti -1c
.RI "void \fBsetShape\fP (\fBShape\fP shape)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file competitorshape.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CompetitorShape::CompetitorShape (intinitialLength, QColor &color, QWidget *parent = \fC0\fP)"
.PP
Definition at line 6 of file competitorshape.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void CompetitorShape::executeUpdate ()\fC [inline, slot]\fP"
.PP
Definition at line 25 of file competitorshape.h.
.SS "void CompetitorShape::paintEvent (QPaintEvent *)\fC [protected]\fP"
.PP
Definition at line 14 of file competitorshape.cpp.
.SS "void CompetitorShape::setRadius (intradius)\fC [inline]\fP"
.PP
Definition at line 19 of file competitorshape.h.
.SS "void CompetitorShape::setShape (\fBShape\fPshape)\fC [inline]\fP"
.PP
Definition at line 20 of file competitorshape.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
