.TH "CompetitorWidget" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompetitorWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <competitorwidget.h>\fP
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBexecuteUpdate\fP (int min_score, int max_score, bool updateScore)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsendUpdate\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompetitorWidget\fP (int circleSize, \fBCompetitor\fP &competitor, \fBDisplayMethodology\fP displayMethodology, QColor color, QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetMaxScore\fP (int max_score)"
.br
.ti -1c
.RI "void \fBsetMinScore\fP (int min_score)"
.br
.ti -1c
.RI "void \fBupdateUsingRatio\fP ()"
.br
.ti -1c
.RI "void \fBupdateUsingRank\fP ()"
.br
.ti -1c
.RI "void \fBupdateUsingRationNormalizedToZero\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file competitorwidget.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CompetitorWidget::CompetitorWidget (intcircleSize, \fBCompetitor\fP &competitor, \fBDisplayMethodology\fPdisplayMethodology, QColorcolor, QWidget *parent = \fC0\fP)"
.PP
Definition at line 10 of file competitorwidget.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void CompetitorWidget::executeUpdate (intmin_score, intmax_score, boolupdateScore)\fC [slot]\fP"
.PP
Definition at line 45 of file competitorwidget.cpp.
.SS "void CompetitorWidget::sendUpdate ()\fC [signal]\fP"
.PP
Definition at line 87 of file moc_competitorwidget.cpp.
.SS "void CompetitorWidget::setMaxScore (intmax_score)\fC [inline]\fP"
.PP
Definition at line 20 of file competitorwidget.h.
.SS "void CompetitorWidget::setMinScore (intmin_score)\fC [inline]\fP"
.PP
Definition at line 21 of file competitorwidget.h.
.SS "void CompetitorWidget::updateUsingRank ()"
.PP
Definition at line 106 of file competitorwidget.cpp.
.SS "void CompetitorWidget::updateUsingRatio ()"
.PP
Definition at line 85 of file competitorwidget.cpp.
.SS "void CompetitorWidget::updateUsingRationNormalizedToZero ()"
.PP
Definition at line 95 of file competitorwidget.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
