.TH "Gui" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gui.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGui\fP (\fBGame\fP &game)"
.br
.ti -1c
.RI "int \fBstart\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file gui.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Gui::Gui (\fBGame\fP &game)"
.PP
Definition at line 15 of file gui.cpp.
.SH "Member Function Documentation"
.PP 
.SS "int Gui::start ()"
.PP
Definition at line 17 of file gui.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
