.TH "/home/nathan/workspace/cooperation/gui.cpp" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nathan/workspace/cooperation/gui.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QtGui>\fP
.br
\fC#include <QFont>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include 'game/game.h'\fP
.br
\fC#include 'gui.h'\fP
.br
\fC#include 'competitorwidget.h'\fP
.br
\fC#include 'mainwindow.h'\fP
.br
\fC#include 'game/common.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
