.TH "/home/nathan/workspace/cooperation/guicommon.h" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nathan/workspace/cooperation/guicommon.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDisplayMethodology\fP { \fBRATIO\fP =  0, \fBRATIO_WITH_MIN_AT_0\fP, \fBRANK\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDisplayMethodology\fP"Determines how GUI displays competitors.
.PP
enum has three values: RATIO Display each competitor's size relative to its points. RATIO_WITH_MIN_AT_0 Same as ratio except subtract the lowest score from every competitor. RANK: Display each competitor's size relative to its rank. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIRATIO \fP\fP
.TP
\fB\fIRATIO_WITH_MIN_AT_0 \fP\fP
.TP
\fB\fIRANK \fP\fP

.PP
Definition at line 13 of file guicommon.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
