.TH "MainWindow" 3 "Sun Apr 1 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (\fBGame\fP &game)"
.br
.ti -1c
.RI "void \fBsetGame\fP (\fBGame\fP &game)"
.br
.ti -1c
.RI "\fBGame\fP & \fBgetGame\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Main window of the GUI. 
.PP
Definition at line 17 of file mainwindow.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (\fBGame\fP &game)"Every main window keeps an instance of a \fBGame\fP that is passed to the constructor. 
.PP
Definition at line 17 of file mainwindow.cpp.
.SH "Member Function Documentation"
.PP 
.SS "\fBGame\fP& MainWindow::getGame () const\fC [inline]\fP"Retrieve the main window's game instance. 
.PP
Definition at line 33 of file mainwindow.h.
.SS "void MainWindow::setGame (\fBGame\fP &game)\fC [inline]\fP"Change the main window's game instance. 
.PP
Definition at line 29 of file mainwindow.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
