.TH "/home/nathan/workspace/cooperation/main.cpp" 3 "Sun Apr 1 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nathan/workspace/cooperation/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/program_options.hpp>\fP
.br
\fC#include 'game/common.h'\fP
.br
\fC#include 'game/game.h'\fP
.br
\fC#include 'gui.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"
.PP
Definition at line 9 of file main.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
