.TH "/home/nathan/workspace/cooperation/release/moc_competitorwidget.cpp" 3 "Sat Mar 31 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nathan/workspace/cooperation/release/moc_competitorwidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../competitorwidget.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
