.TH "/home/nathan/workspace/cooperation/release/moc_definegamedialog.cpp" 3 "Sun Apr 1 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nathan/workspace/cooperation/release/moc_definegamedialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../definegamedialog.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
