.TH "/home/nathan/workspace/cooperation/release/qrc_application.cpp" 3 "Sun Apr 1 2012" "Version 0.1" "Prisoner's Dilemna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nathan/workspace/cooperation/release/qrc_application.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qglobal.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool \fBqRegisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "Q_CORE_EXPORT bool \fBqUnregisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() \fBqInitResources_application\fP ()"
.br
.ti -1c
.RI "int QT_MANGLE_NAMESPACE() \fBqCleanupResources_application\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int QT_MANGLE_NAMESPACE() qCleanupResources_application ()"
.PP
Definition at line 1537 of file qrc_application.cpp.
.SS "QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_application ()"
.PP
Definition at line 1528 of file qrc_application.cpp.
.SS "QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.SS "Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Prisoner's Dilemna from the source code.
